Fix several sparse errors.
A "make C=2 common.o" command produces the following sparse errors:

common.c:6287:1: error: directive in argument list
common.c:6289:1: error: directive in argument list
common.c:6291:1: error: directive in argument list
common.c:6341:1: error: directive in argument list
common.c:6343:1: error: directive in argument list
common.c:6345:1: error: directive in argument list
common.c:4523:22: error: subtraction of different types can't work (different address spaces)
common.c:4695:29: error: subtraction of different types can't work (different address spaces)
common.c:4744:22: error: subtraction of different types can't work (different address spaces)
common.c:4794:22: error: subtraction of different types can't work (different address spaces)
common.c:4843:22: error: subtraction of different types can't work (different address spaces)
common.c:4894:22: error: subtraction of different types can't work (different address spaces)

The first 6 occur because sparse does not like splitting a statement
with #ifdef.
These are of no consequence, but fix them anyway. The remaining 6 will
be fixed later.

The command "make C=2 merge.o" produces the following errors:

merge.c:3060:17: error: incompatible types in conditional expression (different base types)
merge.c:3114:25: error: incompatible types in conditional expression (different base types)

These 2 are "fixed" by changing from "(condition) ? a : b;" to
        if (condition)
                a;
        else
                b;

It seems obvious that these two are a sparse bug, and I will report them
as such.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>