Fix sparse warnings Part 1
A "make C=2" build shows a number of sparse warnings. Not all of them
are easily fixed; however, those that are are fixed here.

Several of the routines got a warning that they were "defined but not
used", and were not used after being converted to static. Those can
eventually be deleted, but for the moment, they are inside #if 0 ..
 #endif directives.

The remaining warnings are:

  CHECK   /home/finger/acx-mac80211/common.c
/home/finger/acx-mac80211/common.c:4522:30: warning: incorrect type in
argument 1 (different address spaces)
/home/finger/acx-mac80211/common.c:4522:30:    expected char const
*<noident>
/home/finger/acx-mac80211/common.c:4522:30:    got char const [noderef]
<asn:1>*buf
/home/finger/acx-mac80211/common.c:4523:22: error: subtraction of
different types can't work (different address spaces)
/home/finger/acx-mac80211/common.c:4695:29: error: subtraction of
different types can't work (different address spaces)
/home/finger/acx-mac80211/common.c:4744:22: error: subtraction of
different types can't work (different address spaces)
/home/finger/acx-mac80211/common.c:4794:22: error: subtraction of
different types can't work (different address spaces)
/home/finger/acx-mac80211/common.c:4843:22: error: subtraction of
different types can't work (different address spaces)
/home/finger/acx-mac80211/common.c:4894:22: error: subtraction of
different types can't work (different address spaces)
  CHECK   /home/finger/acx-mac80211/mem.c
/home/finger/acx-mac80211/mem.c:2524:26: warning: cast removes address
space of expression
/home/finger/acx-mac80211/mem.c:2524:26: warning: incorrect type in
argument 1 (different address spaces)
/home/finger/acx-mac80211/mem.c:2524:26:    expected void volatile
[noderef] <asn:2>*addr
/home/finger/acx-mac80211/mem.c:2524:26:    got void *<noident>
/home/finger/acx-mac80211/mem.c:783:9: warning: context imbalance in
'acxmem_issue_cmd_timeo_debug' - different lock contexts for basic block
/home/finger/acx-mac80211/mem.c:791:12: warning: context imbalance in
'acxmem_complete_hw_reset' - different lock contexts for basic block
/home/finger/acx-mac80211/mem.c:1121:9: warning: context imbalance in
'acxmem_proc_diag_output' - different lock contexts for basic block
/home/finger/acx-mac80211/mem.c:2433:9: warning: context imbalance in
'acxmem_probe' - different lock contexts for basic block
/home/finger/acx-mac80211/mem.c:2615:9: warning: context imbalance in
'acxmem_remove' - different lock contexts for basic block
  CC [M]  /home/finger/acx-mac80211/mem.o
  CHECK   /home/finger/acx-mac80211/merge.c
/home/finger/acx-mac80211/merge.c:469:35: warning: cast removes address
space of expression
/home/finger/acx-mac80211/merge.c:481:43: warning: cast removes address
space of expression
/home/finger/acx-mac80211/merge.c:568:20: warning: cast removes address
space of expression
/home/finger/acx-mac80211/merge.c:1561:32: warning: incorrect type in
assignment (different address spaces)
/home/finger/acx-mac80211/merge.c:1561:32:    expected unsigned char
[noderef] [usertype] <asn:2>*[usertype] cmd_area
/home/finger/acx-mac80211/merge.c:1561:32:    got unsigned char
[usertype] *<noident>
/home/finger/acx-mac80211/merge.c:1562:33: warning: incorrect type in
assignment (different address spaces)
/home/finger/acx-mac80211/merge.c:1562:33:    expected unsigned char
[noderef] [usertype] <asn:2>*[usertype] info_area
/home/finger/acx-mac80211/merge.c:1562:33:    got unsigned char
[usertype] *<noident>
/home/finger/acx-mac80211/merge.c:1566:35: warning: cast removes address
space of expression
/home/finger/acx-mac80211/merge.c:1566:32: warning: incorrect type in
assignment (different address spaces)
/home/finger/acx-mac80211/merge.c:1566:32:    expected unsigned char
[noderef] [usertype] <asn:2>*[usertype] cmd_area
/home/finger/acx-mac80211/merge.c:1566:32:    got unsigned char
[usertype] *
/home/finger/acx-mac80211/merge.c:1567:36: warning: cast removes address
space of expression
/home/finger/acx-mac80211/merge.c:1567:33: warning: incorrect type in
assignment (different address spaces)
/home/finger/acx-mac80211/merge.c:1567:33:    expected unsigned char
[noderef] [usertype] <asn:2>*[usertype] info_area
/home/finger/acx-mac80211/merge.c:1567:33:    got unsigned char
[usertype] *
/home/finger/acx-mac80211/merge.c:160:17: warning: context imbalance in
'acx_upload_radio' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:696:9: warning: context imbalance in
'acx_create_desc_queues' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:887:9: warning: context imbalance in
'acx_proc_eeprom_output' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:1047:9: warning: context imbalance in
'_acx_read_phy_reg' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:1092:9: warning: context imbalance in
'_acx_write_phy_reg' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:1352:17: warning: context imbalance in
'_acx_upload_fw' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:1899:9: warning: context imbalance in
'acx_up' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:2081:9: warning: context imbalance in
'acx_reset_dev' - unexpected unlock
/home/finger/acx-mac80211/merge.c:2134:9: warning: context imbalance in
'acx_verify_init' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:2793:9: warning: context imbalance in
'acxmem_alloc_tx' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:2841:9: warning: context imbalance in
'acxmem_dealloc_tx' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:3271:9: warning: context imbalance in
'_acx_tx_data' - different lock contexts for basic block
/home/finger/acx-mac80211/merge.c:3769:9: warning: context imbalance in
'acx_irq_work' - different lock contexts for basic block
/home/finger/acx-mac80211/interrupt-masks.h:33:26: warning: cast
truncates bits from constant value (ffff10fc becomes 10fc)
/home/finger/acx-mac80211/merge.c:4107:9: warning: context imbalance in
'acx_op_stop' - different lock contexts for basic block

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>