merge.h: Include linux/irq.h
Otherwise build breaks on 3.3 with
---
  CC [M]  acx-mac80211/debugfs.o
In file included from acx-mac80211/debugfs.c:20:0:
acx-mac80211/merge.h:143:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'acx_interrupt'
make[2]: *** [acx-mac80211/debugfs.o] Error 1
---

Signed-off-by: Oliver Winker <oliver@oli1170.net>